version: "3"
services:
  spring-achat:
    image: mariemayadi/ciachat
    ports:
      - "8089:8089"
    networks:
      - net-mysql
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/achatdb
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/mariemdata:/var/lib/mysql:rw
    networks:
      - net-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    security_opt:
      - seccomp:unconfined
     
  angular:
    image: mariemayadi/cifront
    ports:
      - "4200:80"
    networks:
      - net-mysql

networks:
  net-mysql: 
