version: "3"
services:
  spring-jdbc:
    image: yacine96/achat
    ports:
      - "8089:8089"
    networks:
      - employee-mysql
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/achatdb
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/data:/var/lib/mysql
    networks:
      - employee-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD:1
      - MYSQL_DATABASE=achatdb
    security_opt:
      - seccomp:unconfined
      
  angular:
    image: yacine96/angachat
    ports:
      - "4200:80"
    networks:
      - employee-mysql


networks:
  employee-mysql: