version: "3"
services:
  mysqldb:
    image: mysql:8
    networks:
      - achat-network
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD:1
      - MYSQL_DATABASE=achatdb

  achat-jdbc:
    image: mariemayadi/achat
    ports:
      - "8089:8089"
    networks:
      - achat-network
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL:jdbc:mysql://mysqldb/achatdb 
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      
networks:
  achat-network: