version: "3"
services:
  achat-jdbc:
    image: mariemayadi/achat
    ports:
      - "8089:8089"
    networks:
      - achat-mysql
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/achatdb
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/mariemdata:/var/lib/mysql
    networks:
      - achat-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD:1
      - MYSQL_DATABASE=achatdb
    security_opt:
      - seccomp:unconfined

networks:
  achat-mysql: