version: "3"
services:
  spring-jdbc:
    image: yacine96/spring
    ports:
      - "8082:8082"
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: 
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    volumes:
      - /home/mysql/data:/var/lib/mysql
   
